# automated migration configuration file
# test_repo is both the schema and data repo for this migration

# description of the attributes:
# 'files_to_migrate' contains paths to files in the data repo to migrate
# 'schema_repo_url' contains the URL of the schema repo
# 'schema_file' contains the relative path to the schema file in the schema repo
# 'migrator' contains the keyword for the type of migrator to use, a key in `MigrationSpec.MIGRATOR_CREATOR_MAP`
files_to_migrate: [../tests/fixtures//empty_data_file.xlsx]
migrator: wc_lang
schema_file: ../test_repo/core_w_metadata_attr.py
schema_repo_url: https://github.com/KarrLab/test_repo
